// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBUyM4PAc-0ZN0Eh8dV0vbvhaZbTPR0mE',
    appId: '1:393731342360:web:4488eba3e4ef255cad836d',
    messagingSenderId: '393731342360',
    projectId: 'backend-chat-movil-2',
    authDomain: 'backend-chat-movil-2.firebaseapp.com',
    databaseURL: 'https://backend-chat-movil-2-default-rtdb.firebaseio.com',
    storageBucket: 'backend-chat-movil-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfoju_3C89gF1LNzGqaGlo6jlDq3RKsII',
    appId: '1:393731342360:android:cf0984681e500806ad836d',
    messagingSenderId: '393731342360',
    projectId: 'backend-chat-movil-2',
    databaseURL: 'https://backend-chat-movil-2-default-rtdb.firebaseio.com',
    storageBucket: 'backend-chat-movil-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlZ2p5KZj8x7H8eKw-7GFJiOJt5jN1m54',
    appId: '1:393731342360:ios:67d6857c6d5967e3ad836d',
    messagingSenderId: '393731342360',
    projectId: 'backend-chat-movil-2',
    databaseURL: 'https://backend-chat-movil-2-default-rtdb.firebaseio.com',
    storageBucket: 'backend-chat-movil-2.appspot.com',
    iosBundleId: 'com.example.proyectoIntegrador',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlZ2p5KZj8x7H8eKw-7GFJiOJt5jN1m54',
    appId: '1:393731342360:ios:67d6857c6d5967e3ad836d',
    messagingSenderId: '393731342360',
    projectId: 'backend-chat-movil-2',
    databaseURL: 'https://backend-chat-movil-2-default-rtdb.firebaseio.com',
    storageBucket: 'backend-chat-movil-2.appspot.com',
    iosBundleId: 'com.example.proyectoIntegrador',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBUyM4PAc-0ZN0Eh8dV0vbvhaZbTPR0mE',
    appId: '1:393731342360:web:2f945912eddccc14ad836d',
    messagingSenderId: '393731342360',
    projectId: 'backend-chat-movil-2',
    authDomain: 'backend-chat-movil-2.firebaseapp.com',
    databaseURL: 'https://backend-chat-movil-2-default-rtdb.firebaseio.com',
    storageBucket: 'backend-chat-movil-2.appspot.com',
  );
}
